version: "3.8"
services:
  mymongodb:
    image: mongo:latest
    container_name: "airbnb-database"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - airbnb-database